@startuml ModeloDeDominio
skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent
object Usuario{
    nombre
    apellido
    correo
    contraseña
}

object Proponente{
    perfilDocente
    tipoDePerfil

}

object Propuesta{
    objetivo
    funcionamiento
    fstructuraCurricular
    estrategiaEvaluativa
    exigencias
    duracion
    estructuraDeCosto
    cronograma
}

object Aliado{
    tipo
    expediente
}

object "Aval Tecnico" as AT{

}
object administrador {

}

object UCV{
    rif
}

object "Curso de Extensión" as CE{
    nombre
    caracter
    formato
    tipo
    modalidad
    formato
    duracion

}

object "Curso Diplomatico" as CD {

}

Usuario  <|--right administrador
UCV -- administrador
Proponente -- Propuesta
note on link : Realiza
CE *-- Propuesta
Usuario <|--down Proponente
Proponente --up AT
Aliado --right AT
note on link: Produce
Proponente "1..1"-right---"1..3" CE
note on link : Propone
CE <|--right CD
administrador o-- CD
AT -- administrador
note on link : Valida

@enduml